### ISSUE TITLE
How to set default editor and pdfreader?

### ISSUE THREAD

**Issue by bommbo** [ductri/BibMan#1]
same as title.

**Comment by ductri** [comment]
Hi,
Sorry the late response, I didn't get any notification.
 Just in case you're still interested. I've updated to add field 'pdf_reader' to the config file. It's default value is 'zathura', change it to your favorite app, and that's it.

For editor, I made the app with Vim as a very specific editor in mind. Some workflows are tied to Vim, so I don't see the need to use other editor, as that would break some functionalities. 

I've temporarily lost access to pypi, so please install from source code instead.
